### ISSUE TITLE
God Mode Not working

### ISSUE THREAD

**Issue by A9039** [BattleAxeClient/battle-axe-source#1]
**Describe the bug**
God Mode Non Working

**To Reproduce**
1. Enable God Mode

**Expected behavior**
God Mode to work

**Comment by 12brendon34** [comment]
"To Reproduce
Steps to reproduce the behavior:

        1. Enable God Mode
Expected behavior
God Mode to work"

some good info there

**Comment by A9039** [comment]
God Mode almost fixed, committing changes when I am home.
